[package]
name = "upgradeable-v2"
version = "0.1.0"
edition = "2021"
description = "Soroban example v2 implementation used to demonstrate admin-controlled contract upgrades."
keywords = ["soroban", "example", "upgradeable"]
publish = false

[workspace]

[lib]
crate-type = ["cdylib"]
doctest = false

[dependencies]
soroban-sdk = "27.0.3"

[profile.release]
opt-level = "z"
overflow-checks = true
debug = 0
strip = "symbols"
debug-assertions = false
panic = "abort"
codegen-units = 1
lto = true
