[package]
license = "MIT"
name = "simple-voting"
version = "0.1.0"
edition = "2021"
description = "Soroban example voting contract with vote delegation."
keywords = ["soroban", "example", "simple-voting"]

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
soroban-sdk = "27.0.3"

[dev-dependencies]
soroban-sdk = { version = "27.0.3", features = ["testutils"] }
