[package]
name = "escrow-multiparty"
version = "0.1.0"
edition = "2021"
description = "Soroban example multiparty escrow with depositor, recipient, and arbitrator roles."
keywords = ["soroban", "example", "escrow-multiparty"]

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
soroban-sdk = "27.0.3"

[dev-dependencies]
soroban-sdk = { version = "27.0.3", features = ["testutils"] }
