[package]
name = "constant-product-amm"
version = "0.1.0"
edition = "2021"
description = "Soroban example constant-product AMM with add/remove liquidity and token swaps."
keywords = ["soroban", "example", "constant-product-amm"]

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
soroban-sdk = "27.0.3"

[dev-dependencies]
soroban-sdk = { version = "27.0.3", features = ["testutils"] }
