[package]
license = "MIT"
name = "simple-dao"
version = "0.1.0"
edition = "2021"
description = "Soroban example DAO with proposal creation, voting, queuing, and timelocked execution."
keywords = ["soroban", "example", "simple-dao"]

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
soroban-sdk = "27.0.3"

[dev-dependencies]
soroban-sdk = { version = "27.0.3", features = ["testutils"] }
